---
- name: Update Change ticket
  hosts: "{{ public_dns_name | default('localhost') }}"
  gather_facts: false

  tasks:  
    - name: Close change_request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successfully provisioned {{ public_dns_name }}"
        close_notes: "{{ hostvars[public_dns_name] | to_nice_yaml }}"
        assignment_group: "Hardware"
        number: "{{ change_request['record']['number'] }}"
      delegate_to: localhost
