---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create a incident ticket
      servicenow.itsm.incident:
        state: new
        caller: "service.ansible"
        short_description: "{{ incident_short_desc | default('Web app returned a 500 error') }}"
        description: "{{ incident_descr | default('Web Application Experiencing problems') }}"
        impact: high
        urgency: high
      register: itsm_incident

    - ansible.builtin.debug: 
        var: itsm_incident
    
    - name: Pass on incident request artifact
      ansible.builtin.set_stats:
        data:
          incident_request: "{{ itsm_incident.record.number }}"