---
- name: Resolve incident Ticket
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Resolve a incident ticket
      servicenow.itsm.incident:
        state: closed
        number: "{{ incident_request }}"
        close_code: "Closed/Resolved by Caller"
        close_notes: "{{ close_notes | default('Web App was auto remediated by Ansible EDA') }}"