---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create a change request
      servicenow.itsm.change_request:
        type: standard
        state: new
        requested_by: "service.ansible"
        short_description: "Provisioning VM {{ survey_name | default('UBUNTU-VM') }}"
        description: "Provisioning {{ survey_name | default('UBUNTU-VM')}} for user {{ awx_user_name | default('Bob The Builder') }}"
        priority: moderate
        risk: low
        impact: low
        other:
          expected_start: 2021-02-12
      register: itsm_change

    - ansible.builtin.debug: 
        var: itsm_change
    
    - name: Pass on Change request artifact
      ansible.builtin.set_stats:
        data:
          change_request: "{{ itsm_change }}"