---
- name: Update Change ticket
  hosts: localhost
  gather_facts: false

  tasks:  
    - name: Close change_request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successfully provisioned {{ instance_name }}"
        close_notes: "successfully provisioned {{ instance_name }}"
        assignment_group: "Hardware"
        number: "{{ change_request['record']['number'] }}"
      delegate_to: localhost
