---
- name: ACI Create Tenant and query it
  hosts: all
  gather_facts: false

  vars:
    tenant: "Automation_Controller_Test"

  tasks:
    - name: Create a aci tenant
      cisco.aci.aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('ansible.builtin.env', 'ACI_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'ACI_PASSWORD') }}"
        validate_certs: false
        tenant: "{{ tenant }}"
        description: "Test tenant created from Automation Controller"
        state: present
      delegate_to: localhost
    
    - name: Query Tenant
      cisco.aci.aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('ansible.builtin.env', 'ACI_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'ACI_PASSWORD') }}"
        validate_certs: false
        state: query
        tenant: "{{ tenant }}"
        output_level: debug
      delegate_to: localhost
      register: query_result
  
    - name: Show Query Output
      ansible.builtin.debug:
        var: query_result
    
    - name:  Sending slack if failure 
      ansible.builtin.set_stats:
        data:
          artifact: "{{ query_result }}"