--- 
- name: Create a Simple EC2 Instance
  hosts: localhost

  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{instance_name}}"
        region: "{{region}}"
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        security_group: "{{security_group}}"
        vpc_subnet_id: '{{vpc_subnet_id}}'
        network:
          assign_public_ip: true
        image_id: "{{image_id}}"
        tags:
          Environment: aws
      register: instance_name

    - ansible.builtin.debug: 
        var: instance_name
    
    - name: Pass on Instance name artifact
      ansible.builtin.set_stats:
        data:
          instance_name: "{{instance_name}}"
