- name: Connect to terminal server
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test
      opengear_con:
        opengear_host: "ubuntu1.lab.test"
        opengear_user: ""
        opengear_password: ""
        port: 10
        network_user: "admin"
        network_password: "password"
        commands:
          - 'show version'