- name: Network backups
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather IOS configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: ios_config
      when: "'ios' in group_names"

    - name: Gather Aruba configuration
      community.network.aruba_command:
        commands:
          - show running-config
      register: aruba_config
      when: "'aoscx' in group_names"

    - name: Gather Arista configuration
      arista.eos.eos_command:
        commands:
          - show running-config
      register: arista_config
      when: "'eos' in group_names"

    - name: Gather Juniper configuration
      junipernetworks.junos.junos_command:
        commands:
          - show configuration
      register: juniper_config
      when: "'junos' in group_names"

    - name: Set artifact
      ansible.builtin.set_stats:
        data:
          ios:
            name: "{{ inventory_hostname }}"
            ios_config: "{{ ios_config }}"
          aruba:
            name: "{{ inventory_hostname }}"
            aruba_config: "{{ aruba_config }}"
          arista:
            name: "{{ inventory_hostname }}"
            arista_config: "{{ arista_config }}"
          juniper:
            name: "{{ inventory_hostname }}"
            juniper_config: "{{ juniper_config }}"