---
- name: Patch RHEL servers
  hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: dnf_output

    - name: check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      register: reboot_command_check
      ignore_errors: yes

    - name: Need reboot?
      ansible.builtin.set_fact:
        needs_reboot: True
      when: "'Reboot should not be necessary.' not in reboot_command_check.stdout"
    
    - name: Reboot
      ansible.builtin.reboot:
      when: needs_reboot | default(False)
    

