---
- name: Send Slack Notification
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send notification message via Slack
      community.general.slack:
        channel: '{{ slack_channel }}'
        token: '{{ slack_token }}'
        msg: '{{ artifact | to_nice_yaml }}'
