---
- name: Send Slack Notification
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send notification message via Slack
      community.general.slack:
        channel: '#controller-notification'
        token: '{{ slack_token }}'
        msg: '{{ artifact | to_nice_yaml | default("Servers Patched") }}'
