---
- name: Create vCenter Snapshot
  hosts: all
  gather_facts: false

  tasks:
    - name: Create vCenter Snapshot
      community.vmware.vmware_guest_snapshot:
        validate_certs: false
        datacenter: "Datacenter"
        folder: "/Datacenter/vm/"
        state: "{{ state }}"
        name: "{{ inventory_hostname | replace('.lab.test', '') }}"
        snapshot_name: "Pre-Controller-Patching"
        description: "Ansible Controller Patching"
      delegate_to: localhost
